networks:
  proto-default:
    name: proto-default

volumes:
  db:

services:
  app:
    build:
      context: .
    environment:
      FLASK_APP: ${FLASK_APP:-app}
      FLASK_ENV: ${FLASK_ENV:-dev}
      FLASK_DEBUG: ${FLASK_DEBUG:-1}
      LOG_LEVEL: ${LOG_LEVEL:-warning}
    links:
      - db
    container_name: 'proto'
    image: 'prototype:latest'
    ports:
      - ${FLASK_PORTS-9000}:9000
    volumes:
      - './:/home/app/prototype'
    networks:
      - proto-default
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.proto.rule=Host(`prototype.localhost`)"
      - "traefik.docker.network=proto-default"
      - "traefik.http.services.proto.loadbalancer.server.port=9000"



  # Shared database container
  db:
    mem_limit: 2G
    cpus: '2'
    image: mariadb:latest
    container_name: 'proto_db'
    restart: always
    expose:
      - 3306
      - 3308
    ports:
      - ${DB_PORT:-3308}:3306
    environment:
      - MYSQL_USER=local
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=proto
      - MYSQL_ROOT_PASSWORD=root_password
    volumes:
      - db:/var/lib/mysql
      - ./config/mariadb-custom.cnf:/etc/mysql/conf.d/custom.cnf
    networks:
      - proto-default

