volumes:
  db:

services:
  app:
    build:
      context: .
    environment:
      FLASK_APP: ${FLASK_APP:-app}
      FLASK_ENV: ${FLASK_ENV:-dev}
      FLASK_DEBUG: ${FLASK_DEBUG:-1}
      LOG_LEVEL: ${LOG_LEVEL:-warning}
    links:
      - db
    container_name: 'prototype'
    image: 'prototype:latest'
    ports:
      - ${FLASK_PORTS-9000}:9000
    volumes:
      - './:/home/app/prototype'

  # Shared database container
  db:
    mem_limit: 2G
    cpus: '2'
    image: mariadb:latest
    container_name: 'proto_db'
    restart: always
    expose:
      - 3306
    ports:
      - ${DB_PORT:-3308}:3306
    environment:
      - MYSQL_USER=local
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=proto
      - MYSQL_ROOT_PASSWORD=root_password
    volumes:
      - db:/var/lib/mysql
      - ./config/mariadb-custom.cnf:/etc/mysql/conf.d/custom.cnf

