[tool.pyright]
typeCheckingMode = "basic"
reportGeneralTypeIssues = "warning"
reportOptionalMemberAccess = "information"
reportOptionalCall = "information"
reportPrivateImportUsage = "information"

[tool.pytest.ini_options]
testpaths = ["tests"]
log_cli = true
log_level = "INFO"

[tool.ruff]
line-length = 120
ignore = [
    "E711", # Interferes with SQLAlchemy conditions
    "E712", # Interferes with SQLAlchemy conditions
    "E501", # The formatter handles line length, this rule just gets angry at long strings
]

[tool.ruff.per-file-ignores]
"**/routes.py" = ["E501"]
"migrations/**" = ["E501"]

[tool.djlint]
profile = "jinja"
ignore = "J004,J018,H006,H021,H016,H017,H030,H031"
max_line_length = 999
max_attribute_length = 999
blank_line_after_tag = "load,extends,include,csrf_token,endblock,endwith,endif"

# This regex should match all custom-elements with up to 4 words
# This regex should match any number of words but it doesn't work: "\\w+-\\w+(\\-\\w+)+"
custom_html = "\\w+-\\w+,\\w+-\\w+-\\w+,\\w+-\\w+-\\w+-\\w+"

preserve_leading_space = true
format_js = true
format_css = true

[tool.djlint.js]
indent_empty_lines = false
wrap_line_length = 120
brace_style = "preserve-inline"
