"""add tracking tables

Revision ID: 0cad0ccee668
Revises: a8f19aafa0fc
Create Date: 2025-05-30 01:38:12.210085

"""

from alembic import op
import sqlalchemy as sa
import common


# revision identifiers, used by Alembic.
revision = "0cad0ccee668"
down_revision = "a8f19aafa0fc"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "partner",
        sa.Column("name", sa.Text(), nullable=True),
        sa.Column("id", common.database.guid.GUID(), nullable=False),
        sa.Column("language", sa.String(length=5), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "site",
        sa.Column("name", sa.Text(), nullable=True),
        sa.Column("id", common.database.guid.GUID(), nullable=False),
        sa.Column("language", sa.String(length=5), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "tour",
        sa.Column("name", sa.Text(), nullable=True),
        sa.Column("id", common.database.guid.GUID(), nullable=False),
        sa.Column("language", sa.String(length=5), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "track_search",
        sa.Column("user_id", sa.BINARY(length=16), nullable=True),
        sa.Column("partner_id", sa.BINARY(length=16), nullable=True),
        sa.Column("site_id", sa.BINARY(length=16), nullable=True),
        sa.Column("when", sa.DateTime(), nullable=True),
        sa.Column("results", sa.Boolean(), nullable=True),
        sa.Column("filters", sa.JSON(), nullable=True),
        sa.Column("id", common.database.guid.GUID(), nullable=False),
        sa.Column("language", sa.String(length=5), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "track_tour",
        sa.Column("user_id", sa.BINARY(length=16), nullable=True),
        sa.Column("tour_id", sa.BINARY(length=16), nullable=True),
        sa.Column("partner_id", sa.BINARY(length=16), nullable=True),
        sa.Column("site_id", sa.BINARY(length=16), nullable=True),
        sa.Column("departure_date", sa.Date(), nullable=True),
        sa.Column("price", sa.Float(precision=2, asdecimal=True), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=True),
        sa.Column("booked", sa.Boolean(), nullable=True),
        sa.Column("id", common.database.guid.GUID(), nullable=False),
        sa.Column("language", sa.String(length=5), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "track_user",
        sa.Column("partner_id", sa.BINARY(length=16), nullable=True),
        sa.Column("site_id", sa.BINARY(length=16), nullable=True),
        sa.Column("ip", sa.String(length=128), nullable=True),
        sa.Column("country", sa.String(length=128), nullable=True),
        sa.Column("id", common.database.guid.GUID(), nullable=False),
        sa.Column("language", sa.String(length=5), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "user",
        sa.Column("name", sa.Text(), nullable=True),
        sa.Column("id", common.database.guid.GUID(), nullable=False),
        sa.Column("language", sa.String(length=5), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user")
    op.drop_table("track_user")
    op.drop_table("track_tour")
    op.drop_table("track_search")
    op.drop_table("tour")
    op.drop_table("site")
    op.drop_table("partner")
    # ### end Alembic commands ###
