"""Add Measurement table

Revision ID: a8f19aafa0fc
Revises: 
Create Date: 2025-05-20 00:04:05.037264

"""
from alembic import op
import sqlalchemy as sa
from common.database.guid import GUID

# revision identifiers, used by Alembic.
revision = 'a8f19aafa0fc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('measurement',
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('id', GUID(), nullable=False),
    sa.Column('language', sa.String(length=5), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('measurement')
    # ### end Alembic commands ###
